### ISSUE TITLE
Plugin fails to print from Cura 2.5

### ISSUE THREAD

**Issue by godefroi** [fieldOfView/OctoPrintPlugin#32] opened 2017-04-13 00:38 UTC
I'm using the 2.5 branch of the plugin with the Cura 2.5 beta, and while Cura will communicate with the printer and retrieve status just fine, it won't print. The progress bar appears momentarily, but OctoPrint never receives the file.

**Comment by fieldOfView** [comment] 2017-04-13 06:17
Are you using the 2.5 branch? You must use the branch that matches the Cura version

**Comment by godefroi** [comment] 2017-04-13 15:46
Yep, definitely. I updated it yesterday just to be sure.

**Comment by fieldOfView** [comment] 2017-04-13 19:11
Sorry for the cookie-cutter answer before. I'll look into it.
You haven't by chance enabled the SD-card option, have you?

**Comment by godefroi** [comment] 2017-04-13 19:50
I'm not sure what you mean by that. I don't have an SD card in my printer, and I've never printed from an SD before.

**Comment by fieldOfView** [comment] 2017-04-13 20:33
I was referring to a checkbox in the Connect OctoPrint interface.

**Comment by godefroi** [comment] 2017-04-13 23:21
Ah. No, the option is not selected. The "Automatically start..." box is selected, and the "Show webcam..." is not selected (though it seems to me that in previous 2.3 versions it must have defaulted to selected).

Cura correctly shows all the telemetry from OctoPrint (temperatures, status, job name, etc) on the printer tab.

**Comment by godefroi** [comment] 2017-04-18 01:37
More information: if I take an .STL on my hard drive, slice in Cura, and "Print to OctoPrint", it works great. If I model something in Fusion 360, "Save as STL" (which can send to Cura), then try to "Print to OctoPrint", it doesn't work.

**Comment by fieldOfView** [comment] 2017-04-18 06:46
Thanks, that is helpfull info.

I vaguely remember from an issue with Cura that when sending the print to Cura directly from Fusion 360, the filename comes in a something like {aec797d8-a1e8-45b5-8c47-4e9b949c7d95}.stl, which sets the job name in the lower right corner to {aec797d8-a1e8-45b5-8c47-4e9b949c7d95}, am I right? I guess the problem lies with the curly brackets. 

A workaround for now would be to remove them from the jobname in the lower right corner (you can edit that jobname just by clicking on it). If that fixes the issue for you, I will make sure the plugin sanitizes the jobname before sending it to OctoPrint.

**Comment by fieldOfView** [comment] 2017-04-18 07:11
Hmm, turns out there are no curly brackets. It might be the filename/jobname length then.

**Comment by fieldOfView** [comment] 2017-04-18 09:51
Anything helpful in the logs? I cannot reproduce this.

**Comment by godefroi** [comment] 2017-04-18 14:31
I'll get back to you today. Where could I look for logs?

**Comment by fieldOfView** [comment] 2017-04-18 14:42
In Cura, see Help -> Show Configuration Folder

There should be a file named Cura.log, which is probably fairly big. Please close Cura, remove that file, and then try printing through Fusion 360 -> Cura -> OctoPrint. Then close Cura, and post the log file, eg on pastebin.com

**Comment by fieldOfView** [comment] 2017-04-18 14:43
So it worked with 2.3, but not with 2.5? Did you try 2.4?

**Comment by godefroi** [comment] 2017-04-19 02:37
I never did try 2.4. Here's the cura.log: https://pastebin.com/CRj7RSqG

There's a stderr file as well, it seems to mostly have the same information.

**Comment by godefroi** [comment] 2017-04-19 02:39
Aha! Solid progress! If I enter a job name and *then* print, it works just fine.

**Comment by fieldOfView** [comment] 2017-04-19 13:06
Thanks for debugging. The issue is with Cura (which does not set a proper "jobname" when loading an object by specifying the filename in the command line), but I have added a workaround for the resulting issue.

Could you redownload the 2.5 version and try again?

**Comment by fieldOfView** [comment] 2017-04-19 13:16
See https://github.com/Ultimaker/Cura/issues/1703

**Comment by godefroi** [comment] 2017-04-20 12:55
Success. The job name is empty in Cura (as was your intent, I'm sure) and shows up in octoprint as untitled_print.gcode, and prints successfully. Thank you!

**Comment by fieldOfView** [comment] 2017-04-20 13:02
> The job name is empty in Cura (as was your intent, I'm sure)

The empty jobname is not something I can fix from the side of the OctoPrintPlugin, and will need to be fixed inside Cura. I have just worked around the issue here (and hope the workaround becomes superfluous over time). Thanks for reporting!

**Closed by fieldOfView** 2017-04-20 13:02 UTC
