### ISSUE TITLE
Time and percent complete are incorrect

### ISSUE THREAD

**Issue by critter42** [fieldOfView/OctoPrintPlugin#91] opened 2018-11-08 13:55 UTC
Every file I send to Octoprint has a time estimate that is double what Cura shows. Additionally, the model has completed printing, but Octoprint and Cura show it is 50% done, so I have to "abort print"  - it is like it is trying to print 2 copies all the time.

![image](https://user-images.githubusercontent.com/3156405/48202832-98b68f00-e32b-11e8-940e-25490d524863.png)

**Comment by fieldOfView** [comment] 2018-11-08 13:59
Does the same happen if you save the gcode, upload it to OctoPrint through the web interface and print it from there? If so, I don't think there's anything the OctoPrint Connection plugin can do about this; the plugin seems to show exactly what OctoPrint is showing.

**Comment by fieldOfView** [comment] 2018-12-04 09:56
I'm going to assume this is indeed a duplicate of #94. Feel free to reopen if the version that is currently published to the Marketplace in Cura does not fix it.

**Closed by fieldOfView** 2018-12-04 09:56 UTC
Labels: info needed
