### ISSUE TITLE
Plugin does not work with 2.4 version

### ISSUE THREAD

**Issue by osmunda** [fieldOfView/OctoPrintPlugin#26] opened 2017-03-02 16:07 UTC
The plugin works fine with 2.3.1 but not with the new version 2.4. Connection with octoprint is made (I can see the webcam, temperatures, etc) but nothing happens when click "print with Octoprint"

**Comment by fieldOfView** [comment] 2017-03-02 16:10
Please use the 2.4 branch of this plugin when using Cura 2.4.

Duplicate of https://github.com/fieldOfView/OctoPrintPlugin/issues/24

**Closed by fieldOfView** 2017-03-02 16:10 UTC
